development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  # pool: 360
  # checkout_timeout: 720
  database: wallpapers_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: wallpapers_test
  # pool: 50
  username: root
  password: