development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: wallpapers_development
  pool: 360
  checkout_timeout: 720
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: wallpapers_test
  pool: 50
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: wallpapers_production
  pool: 50
  username: root
  password:
  socket: /tmp/mysql.sock
