development:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  pool: 360
  checkout_timeout: 720
  database: wallpapers_development
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: wallpapers_test
  pool: 50
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  reconnect: true
  database: wallpapers_production
  pool: 50
  host: 54.235.194.194
  username: wallpapers
  password: 6ivqxTkK6m